export const choujiangConfig = [
    {
        id: 0,
        itemId: 0,
        cnt: 100,
        weight: 20,
    },
    {
        id: 1,
        itemId: 0,
        cnt: 200,
        weight: 15,
    },
    {
        id: 2,
        itemId: 0,
        cnt: 500,
        weight: 10,
    },
    {
        id: 3,
        itemId: 0,
        cnt: 800,
        weight: 5,
    },
    {
        id: 4,
        itemId: 1,
        cnt: 1,
        weight: 10,
    },
    {
        id: 5,
        itemId: 2,
        cnt: 1,
        weight: 20,
    },
    {
        id: 6,
        itemId: 3,
        cnt: 1,
        weight: 15,
    },
    {
        id: 7,
        itemId: 4,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 8,
        itemId: 5,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 9,
        itemId: 6,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 10,
        itemId: 7,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 11,
        itemId: 8,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 12,
        itemId: 9,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 13,
        itemId: 10,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 14,
        itemId: 11,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 15,
        itemId: 12,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 16,
        itemId: 13,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 17,
        itemId: 14,
        cnt: 1,
        weight: 0.5,
    },
    {
        id: 18,
        itemId: 15,
        cnt: 1,
        weight: 0.5,
    },
]
