/**
 * 关卡配置
 * @param fenzu 每组3个球，组数越多当前关卡球的数量越多
 * @param catFenzu 猫分组，代表当前关卡出现几组猫类型的球
 * @param peiduiFenzu 配对分组，数值不能超过fenzu的值，值越小难度越大
 */
export const putongLevelConfig = [
    // 1-10关
    {
        id: 1,
        fenzu: 3,
        catFenzu: 1,
        peiduiFenzu: 3,
        time: 30,
    },
    {
        id: 2,
        fenzu: 80,
        catFenzu: 0,
        peiduiFenzu: 50,
        time: 350,
    },
    {
        id: 3,
        fenzu: 30,
        catFenzu: 0,
        peiduiFenzu: 25,
        time: 118,
    },
    {
        id: 4,
        fenzu: 40,
        catFenzu: 0,
        peiduiFenzu: 36,
        time: 130,
    },
    {
        id: 5,
        fenzu: 40,
        catFenzu: 6,
        peiduiFenzu: 20,
        time: 140,
    },
    {
        id: 6,
        fenzu: 30,
        catFenzu: 0,
        peiduiFenzu: 12,
        time: 120,
    },
    {
        id: 7,
        fenzu: 32,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 135,
    },
    {
        id: 8,
        fenzu: 34,
        catFenzu: 0,
        peiduiFenzu: 8,
        time: 135,
    },
    {
        id: 9,
        fenzu: 36,
        catFenzu: 0,
        peiduiFenzu: 8,
        time: 138
    },
    {
        id: 10,
        fenzu: 40,
        catFenzu: 6,
        peiduiFenzu: 10,
        time: 125,
    },
    {
        id: 11,
        fenzu: 31,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 170,
    },
    {
        id: 12,
        fenzu: 32,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 172,
    },
    {
        id: 13,
        fenzu: 33,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 174,
    },
    {
        id: 14,
        fenzu: 34,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 178,
    },
    {
        id: 15,
        fenzu: 35,
        catFenzu: 10,
        peiduiFenzu: 0,
        time: 80,
    },
    {
        id: 16,
        fenzu: 36,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 145,
    },
    {
        id: 17,
        fenzu: 37,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 146,
    },
    {
        id: 18,
        fenzu: 38,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 148,
    },
    {
        id: 19,
        fenzu: 39,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 154,
    },
    {
        id: 20,
        fenzu: 40,
        catFenzu: 10,
        peiduiFenzu: 0,
        time: 95,
    },
    {
        id: 21,
        fenzu: 41,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 160,
    },
    {
        id: 22,
        fenzu: 42,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 160,
    },
    {
        id: 23,
        fenzu: 43,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 160,
    },
    {
        id: 24,
        fenzu: 44,
        catFenzu: 0,
        peiduiFenzu: 0,
        time: 162,
    },
    {
        id: 25,
        fenzu: 45,
        catFenzu: 10,
        peiduiFenzu: 0,
        time: 95,
    },
    {
        id: 26,
        fenzu: 46,
        catFenzu: 0,
        peiduiFenzu: 6,
        time: 164,
    },
    {
        id: 27,
        fenzu: 47,
        catFenzu: 0,
        peiduiFenzu: 6,
        time: 168,
    },
    {
        id: 28,
        fenzu: 48,
        catFenzu: 0,
        peiduiFenzu: 6,
        time: 170,
    },
    {
        id: 29,
        fenzu: 49,
        catFenzu: 0,
        peiduiFenzu: 6,
        time: 170,
    },
    {
        id: 30,
        fenzu: 50,
        catFenzu: 10,
        peiduiFenzu: 0,
        time: 105,
    },
    {
        id: 31,
        fenzu: 61,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 234,
    },
    {
        id: 32,
        fenzu: 62,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 236,
    },
    {
        id: 33,
        fenzu: 63,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 236,
    },
    {
        id: 34,
        fenzu: 64,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 236,
    },
    {
        id: 35,
        fenzu: 65,
        catFenzu: 10,
        peiduiFenzu: 10,
        time: 190,
    },
    {
        id: 36,
        fenzu: 66,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 240,
    },
    {
        id: 37,
        fenzu: 67,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 240,
    },
    {
        id: 38,
        fenzu: 68,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 260,
    },
    {
        id: 39,
        fenzu: 69,
        catFenzu: 0,
        peiduiFenzu: 10,
        time: 260,
    },
    {
        id: 40,
        fenzu: 70,
        catFenzu: 10,
        peiduiFenzu: 10,
        time: 200,
    },
    {
        id: 41,
        fenzu: 71,
        catFenzu: 0,
        peiduiFenzu: 9,
        time: 350,
    },
    {
        id: 42,
        fenzu: 72,
        catFenzu: 0,
        peiduiFenzu: 8,
        time: 350,
    },
    {
        id: 43,
        fenzu: 73,
        catFenzu: 0,
        peiduiFenzu: 7,
        time: 350,
    },
    {
        id: 44,
        fenzu: 74,
        catFenzu: 0,
        peiduiFenzu: 6,
        time: 355,
    },
    {
        id: 45,
        fenzu: 75,
        catFenzu: 10,
        peiduiFenzu: 5,
        time: 230,
    },
    {
        id: 46,
        fenzu: 76,
        catFenzu: 0,
        peiduiFenzu: 5,
        time: 360,
    },
    {
        id: 47,
        fenzu: 77,
        catFenzu: 0,
        peiduiFenzu: 5,
        time: 360,
    },
    {
        id: 48,
        fenzu: 78,
        catFenzu: 0,
        peiduiFenzu: 5,
        time: 365,
    },
    {
        id: 49,
        fenzu: 79,
        catFenzu: 0,
        peiduiFenzu: 5,
        time: 365,
    },
    {
        id: 50,
        fenzu: 80,
        catFenzu: 10,
        peiduiFenzu: 0,
        time: 230,
    },
    {
        id: 51,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 40,
        time: 520,
    },
    {
        id: 52,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 38,
        time: 520,
    },
    {
        id: 53,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 36,
        time: 525,
    },
    {
        id: 54,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 35,
        time: 525,
    },
    {
        id: 55,
        fenzu: 90,
        catFenzu: 10,
        peiduiFenzu: 34,
        time: 260,
    },
    {
        id: 56,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 33,
        time: 530,
    },
    {
        id: 57,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 530,
    },
    {
        id: 58,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 31,
        time: 535,
    },
    {
        id: 59,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 30,
        time: 535,
    },
    {
        id: 60,
        fenzu: 90,
        catFenzu: 10,
        peiduiFenzu: 10,
        time: 290,
    },
    {
        id: 61,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 530,
    },
    {
        id: 62,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 525,
    },
    {
        id: 63,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 520,
    },
    {
        id: 64,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 515,
    },
    {
        id: 65,
        fenzu: 90,
        catFenzu: 10,
        peiduiFenzu: 10,
        time: 280,
    },
    {
        id: 66,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 510,
    },
    {
        id: 67,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 505
    },
    {
        id: 68,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 500,
    },
    {
        id: 69,
        fenzu: 90,
        catFenzu: 0,
        peiduiFenzu: 32,
        time: 495,
    },
    {
        id: 70,
        fenzu: 90,
        catFenzu: 12,
        peiduiFenzu: 0,
        time: 290
    },
]
/**
 * 挑战模式关卡
 */
export const tiaozhanLevelConfig = [
    {
        id: 1,
        fenzu: 3,
        time: -1,
        peiduiFenzu: 0,
    },
    {
        id: 2,
        fenzu: 150,
        time: 500,
        peiduiFenzu: 80,
    },
]
